import React from 'react'

const CookiePolicy = () => {
  return (
<div className="w-full p-6 rounded-md shadow-md overflow-auto">
        <div className="flex items-center mb-6">
          <h3 className="text-[24px] font-bold text-black">
Cookie Policy          </h3>
        </div>
        <div className="relative overflow-x-auto bg-white shadow-customShadow rounded-md p-8 mb-2 text-black overflow-auto">
          <span className="w-full h-[272px] bg-gradient-to-t from-[#FFFF]/[1] to-[#FFFF]/[0] absolute bottom-0 rounded-b-[16px] left-0 overflow-auto"></span>

          <h1 className="text-[24px] font-semibold pb-2">
    Definitions and Key Terms
</h1>
<p className="text-[18px]">
    To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, they are strictly defined as:
</p>
<ul className="text-[18px] list-disc pl-5">
    <li>
        <strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.
    </li>
    <li>
        <strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Dr. Hau, which is responsible for your information under this Cookie Policy.
    </li>
    <li>
        <strong>Device:</strong> any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Dr. Hau and use the services.
    </li>
    <li>
        <strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information—including a personal identification number—allows for the identification or identifiability of a natural person.
    </li>
    <li>
        <strong>Service:</strong> refers to the service provided by Dr. Hau as described in the relevant terms (if available) and on this platform.
    </li>
    <li>
        <strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
    </li>
    <li>
        <strong>Website:</strong> Dr. Hau’s site, which can be accessed via this URL: <a href="https://www.dignitestudios.com/" className="text-blue-500">https://www.dignitestudios.com/</a>
    </li>
    <li>
        <strong>You:</strong> a person or entity that is registered with Dr. Hau to use the Services.
    </li>
</ul>
<p className="text-[18px]">
    This Cookie Policy was created by Dignite Studios.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    Introduction
</h1>
<p className="text-[18px]">
    This Cookie Policy explains how Dr. Hau and its affiliates (collectively "Dr. Hau", "we", "us", and "ours") use cookies and similar technologies to recognize you when you visit our website, including without limitation <a href="https://www.dignitestudios.com/" className="text-blue-500">https://www.dignitestudios.com/</a> and any related URLs, mobile or localized versions, and related domains/sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    What is a Cookie?
</h1>
<p className="text-[18px]">
    A cookie is a small text file that is stored on your computer or other internet-connected device in order to identify your browser, provide analytics, and remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    Why Do We Use Cookies?
</h1>
<p className="text-[18px]">
    We use first-party and/or third-party cookies on our website for various purposes such as:
</p>
<ul className="text-[18px] list-disc pl-5">
    <li>To facilitate the operation and functionality of our website;</li>
    <li>To improve your experience of our website and make navigating around them quicker and easier;</li>
    <li>To allow us to create a bespoke user experience for you and for us to understand what is useful or of interest to you;</li>
    <li>To analyze how our website is used and how best we can customize it;</li>
    <li>To identify future prospects and personalize marketing and sales interactions;</li>
    <li>To facilitate the tailoring of online advertising to your interests.</li>
</ul>

<h1 className="text-[24px] font-semibold pb-2">
    What Type of Cookies Does Dr. Hau Use?
</h1>
<p className="text-[18px]">
    Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called "first-party cookies."
</p>
<p className="text-[18px]">
    <strong>Strictly Necessary Cookies:</strong> These are necessary for our website to function and cannot be switched off in our systems. They are essential for you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    We Use the Following Types of Cookies on Our Website:
</h1>

<h2 className="text-[20px] font-semibold pb-1">
    Essential Cookies
</h2>
<p className="text-[18px]">
    We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences, and accessibility. Without them, you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.
</p>

<h2 className="text-[20px] font-semibold pb-1">
    Performance and Functionality Cookies
</h2>
<p className="text-[18px]">
    These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionalities like videos may become unavailable, or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.
</p>

<h2 className="text-[20px] font-semibold pb-1">
    Third Party Cookies
</h2>
<p className="text-[18px]">
    Some cookies that have been set on our website are not set on a first-party basis by Dr. Hau. The Websites can be embedded with content from third parties to serve advertising. These third-party service providers may set their own cookies on your web browser. Third-party service providers control many of the performance and functionality, advertising, marketing, and analytics cookies described above. We do not control the use of these third-party cookies as cookies can only be accessed by the third party that originally set them.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    How You Can Manage Cookies
</h1>
<p className="text-[18px]">
    Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.
</p>
<p className="text-[18px]">
    Please see below for more information:
</p>
<ul className="text-[18px] list-disc pl-5">
    <li>Google Chrome</li>
    <li>Internet Explorer</li>
    <li>Mozilla Firefox</li>
    <li>Safari (Desktop)</li>
    <li>Safari (Mobile)</li>
    <li>Android Browser</li>
    <li>Opera</li>
    <li>Opera Mobile</li>
</ul>

<h1 className="text-[24px] font-semibold pb-2">
    Blocking and Disabling Cookies and Similar Technologies
</h1>
<p className="text-[18px]">
    Wherever you're located, you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly. You may not be able to fully utilize all of its features and services. You should also be aware that you may lose some saved information (e.g., saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser; you will need to do this yourself from within your browser. Please visit your browser's help menu for more information.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    Changes to Our Cookie Policy
</h1>
<p className="text-[18px]">
    We may change our Service and policies, and we may need to make changes to this Cookie Policy to accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. If you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    Your Consent
</h1>
<p className="text-[18px]">
    By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.
</p>

<h1 className="text-[24px] font-semibold pb-2">
    Contact Us
</h1>
<p className="text-[18px]">
    Don't hesitate to contact us if you have any questions regarding our Cookie Policy.
</p>
<ul className="text-[18px] list-disc pl-5">
    <li>Via Email: <a href="mailto:drhau@sculptdtla.com" className="text-blue-500">drhau@sculptdtla.com</a></li>
    <li>Via Phone Number: 213-265-7285</li>
    <li>Via this Link: <a href="https://www.dignitestudios.com/" className="text-blue-500">https://www.dignitestudios.com/</a></li>
    <li>Via this Address: 700 W 7th Street G240, Los Angeles, CA 90017</li>
</ul>


          </div>
          </div>
           )
}

export default CookiePolicy;